= Assignment 2 Part 2
Ryan Chalmers

== Question 1

In the two phase simplex method we must first find if the problem has any
feasible solutions. In this phase we cannot pivot out the auxiliary variable,
therefore can only choose between  to constraints giving

*C(n+m, m-1) = C(3 + 15, 2) = C(18, 2) + 1= 154* +

Now assuming the result from the the first phase gives us
a feasible starting solution we can begin finding the optimal feasible solution.
Since we know that the LP has an optimal feasible solution we can know there is
a finite number of dictionaries. More specifically there are; +

*C(n+m, m) = C(3 + 15, 3) = C(18, 3) = 816* +

Therefore at the maximum iterations possible to find the optimal feasible
solution is 970. This is assuming we avoid cycling using the smallest
subscript rule. Taking this into account you should be wiling to
pay is $109.70.

== Question 2

The basic solution to the problem (4,0,0,7,0,0,11,15,10,0,0,3,4,6,0) is not
possible. This is the case because the problem is formulated with only 3
constraints, and therefore only three basic variables. To find a feasible
solution to a dictionary we must set all the
non basic variable of the dictionary to 0 find values for basic variables.
Therefore we could only solve for the values of three variables at a time
because we only have three equations (minus the objective function) coming
from the constraints. Therefore we should have a maximum of 3 non-zero variables
in the basic solution.

== Question 3

We use the fact that if the primal of an LP is unbounded then the dual of the
LP is infeasible. +
x~6~ = 7 - x~1~ + 3x~4~ + x~5~ +
x~2~ = 9 + 3x~1~ + 3x~4~ - 3x~5~ +
x~3~ = 12 - x~1~ + 5x~4~ - 11x~5~ +
z = 562 + 24x~1~ + 5x~4~ - 7x~5~ +
By looking at the above dictionary we can deduce that the variable x~4~ is
unbounded. Since the dual is attempting to approximate an upper bound on the
primal, if the primal is unbounded then the dual will have no solution.

== Question 4


For the first phase of the simplex we have family F of the form: +
{z, x~1~,x~2~,x~3~,...} +
{z, x~1~,x~5~,x~3~,...} +
{z, x~1~,x~5~,x~6~,...} +
Where each entry is of size m with consisting of P+z, thus p is defined as: +
P~1~={x~1~,x~2~,x~3~,...} +
P~2~={x~1~,x~5~,x~3~,...} +
P~3~={x~1~,x~5~,x~6~,...} +
We are trying to find a bijection between this set and the degenerate sets
created when solving a dictionary in the second phase of the simplex method: +
{0, x~1~,x~2~,x~3~,...} +
{0, x~1~,x~5~,x~3~,...} +
{0, x~1~,x~5~,x~6~,...} +
At maximum the number n of degenerate dictionaries is less than or equal to the
the number of of dictionaries in F consisting of P. We get this by setting the
values of z to 0 in the first form the simplex method.
